file1 = open("demo.txt", "w")
file1.write("Avodha is the best platform to study job oriented courses")
file1.close()
file1 = open("demo.txt", "r")
a = file1.read()
print(a)
file1.close()
file1 = open("demo.txt", "a")
file1.write("\nAvodha provide courses like Python, Digital marketing, Fullstack development etc")
file1.close()
